# Config file for DeepForest-pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 20
gpus: 7
distributed_backend: ddp

batch_size: 10
nms_thresh: 0.15
score_thresh: 0.2
train:
    csv_file: /orange/ewhite/b.weinstein/NeonTreeEvaluation/pretraining/crops/pretraining.csv
    root_dir: /orange/ewhite/b.weinstein/NeonTreeEvaluation/pretraining/crops/
    
    #Optomizer  initial learning rate
    lr: 0.0001
    
    #Print loss every n epochs
    print_freq: 1
    epochs: 4
    
    #Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False
 
validation:
    #callback args
    csv_file: /orange/idtrees-collab/NeonTreeEvaluation/evaluation/RGB/benchmark_annotations.csv
    root_dir: /orange/idtrees-collab/NeonTreeEvaluation/evaluation/RGB/
    #Intersection over union evaluation
    iou_threshold: 0.4
