# Config file for DeepForest-pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 15
gpus: 3
distributed_backend: ddp

batch_size: 3
nms_thresh: 0.15
score_thresh: 0.25
train:
    csv_file: /orange/ewhite/b.weinstein/Radogoshi_Sweden/train.csv
    root_dir: /orange/ewhite/b.weinstein/Radogoshi_Sweden/images/
    
    #Optomizer  initial learning rate
    lr: 0.001
    
    #Print loss every n epochs
    print_freq: 1
    epochs: 15
    
    #Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False
 
validation:
    #callback args
    csv_file: /orange/ewhite/b.weinstein/Radogoshi_Sweden/test.csv
    root_dir: /orange/ewhite/b.weinstein/Radogoshi_Sweden/images/
    #Intersection over union evaluation
    iou_threshold: 0.4
